//Alertas
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

//Usuarios
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION= 'CERRAR_SESION';

//Productos
export const OBTENER_PRODUCTO = 'OBTENER_PRODUCTO';
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';
export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';

//Mesas
export const OBTENER_MESAS = 'OBTENER_MESAS';
export const MESA_ACTUAL = 'MESA_ACTUAL';
export const OBTENER_MESA_ACTUAL = 'OBTENER_MESA_ACTUAL';
export const MESA_ENTREGAR_PEDIDO = 'MESA_ENTREGAR_PEDIDO';
export const MESA_OBTENER_PEDIDO = 'MESA_OBTENER_PEDIDO';
export const ELIMINAR_PEDIDO = 'ELIMINAR_PEDIDO';

//Pedidos
export const OBTENER_PEDIDO = 'OBTENER_PEDIDO';
export const ELIMINAR_PRODUCTO_PEDIDO = 'ELIMINAR_PRODUCTO_PEDIDO';
export const AGREGAR_PRODUCTO_PEDIDO = 'AGREGAR_PRODUCTO_PEDIDO';
export const OTORGAR_PEDIDO = 'OTORGAR_PEDIDO'